FROM node:gallium-slim

WORKDIR /app

COPY . .

# Install python/pip
ENV PYTHONUNBUFFERED=1
RUN apt update -y && \
    apt install -y python3 g++ make libsqlite3-dev && \
    ln -sf python3 /usr/bin/python && \
    npm i --build-from-source --sqlite=/usr/local --save sqlite3@5.0 && \
    npm i && \
    npm rebuild && \
    npm run build && \
    npm prune --production && \
    rm -rf api charts mocks index.ts && \
    cp -R dist/* /app && \
    apt purge -y python3 g++ make && \
    apt autoremove -y

ENV DB_PATH=/data/db.sqlite
ENV APP_PORT=3000

CMD [ "node", "index.js" ]
