{{- with .Values.simplesecrets }}

apiVersion: apps/v1
kind: Deployment
metadata:
    name: simplesecrets-api
    namespace: {{ $.Release.Namespace }}
    labels:
        app: simplesecrets-api
spec:
    replicas: 1
    selector:
        matchLabels:
            app: simplesecrets-api
    template:
        metadata:
            labels:
                app: simplesecrets-api
        spec:
            serviceAccountName: k8s-101-role
            containers:
                - name: api
                  image: {{ .image }}:{{ .tag }}
                  imagePullPolicy: IfNotPresent
                  env:
                          - name: DB_PATH
                            value: "/data/db.sqlite"
                          - name: APP_PORT
                            value: {{ .port }}
{{- if .resources }}
                  resources:
{{ toYaml .resources | indent 22 }}
{{- end }}
                  ports:
                      - name: api
                        containerPort: {{ .port }}
                  volumeMounts:
                      - name: data-config
                        mountPath: /data
                  livenessProbe:
                      failureThreshold: 2
                      initialDelaySeconds: 120
                      periodSeconds: 120
                      timeoutSeconds: 5
                      tcpSocket:
                          port: {{ .port }}
            restartPolicy: Always
            volumes:
                {{- if .dataPvc }}
                - name: data
                  persistentVolumeClaim:
                      claimName: {{ .dataPvc }}
                {{- else }}
                - name: data-config
                  hostPath:
                      path: /tmp/ss/data
                {{- end }}

---

apiVersion: v1
kind: Service
metadata:
    name: simplesecrets-api
    namespace: {{ $.Release.Namespace }}
spec:
    selector:
        app: simplesecrets-api
    ports:
        - name: api
          protocol: TCP
          port: {{ .port }}

{{- end }}
