apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
    name: simple-secrets-ingress
    namespace: {{ $.Release.Namespace }}
spec:
    podSelector:
        matchLabels:
            role: simplesecrets-api
    policyTypes:
        - Ingress
    ingress:
        - from:
              - namespaceSelector:
                    matchLabels:
                        kubernetes.io/metadata.name: {{ $.Release.Namespace }}
              - podSelector:
                    matchLabels:
                        app: simplesecrets-web

          ports:
              - protocol: TCP
                port: 80