{{- with .Values.simplesecrets }}

apiVersion: apps/v1
kind: Deployment
metadata:
    name: simplesecrets-web
    namespace: {{ $.Release.Namespace }}
    labels:
        app: simplesecrets-web
spec:
    replicas: 1
    selector:
        matchLabels:
            app: simplesecrets-web
    template:
        metadata:
            labels:
                app: simplesecrets-web
        spec:
            containers:
                - name: web
                  image: {{ .image }}:{{ .tag }}
                  imagePullPolicy: IfNotPresent
{{- if .resources }}
                  resources:
{{ toYaml .resources | indent 22 }}
{{- end }}
                  ports:
                      - name: web
                        containerPort: {{ .port }}
                  livenessProbe:
                      failureThreshold: 2
                      initialDelaySeconds: 120
                      periodSeconds: 120
                      timeoutSeconds: 5
                      tcpSocket:
                          port: {{ .port }}
            restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
    name: simplesecrets-web
    namespace: {{ $.Release.Namespace }}
spec:
    type: LoadBalancer
    selector:
        app: simplesecrets-web
    ports:
        - name: web
          protocol: TCP
          port: {{ .port }}

{{- end }}
