simplesecrets:
    image: stefangenov/simplesecrets
    tag: 0.1.0
    #    nodePort: 30125
    port: 80
    resources:
        requests:
            cpu: 1
            memory: 1Gi
        limits:
            cpu: 2
            memory: 2Gi

storage:
    dataLocality: "best-effort" # or disabled
    numberOfReplicas: 1
    configSize: 1Gi
