simplesecrets:
    image: stefangenov/simplesecrets
    tag: 1.0.2
    #    nodePort: 30125
    port: 80
    resources:
        requests:
            cpu: 10m
            memory: 100Mi
        limits:
            cpu: 100m
            memory: 500Mi

storage:
    dataLocality: "best-effort" # or disabled
    numberOfReplicas: 1
    configSize: 1Gi
