simplesecrets:
    api:
        image: stefangenov/simplesecrets
        tag: 2.1.0
        port: 80
        resources:
            requests:
                cpu: 200m
                memory: 200Mi
    web:
        image: stefangenov/simplesecrets-frontend
        tag: 1.0.0
        port: 3000
        resources:
            requests:
                cpu: 100m
                memory: 100Mi
