simplesecrets:
    api:
        image: stefangenov/simplesecrets
        tag: 1.0.9-sqlite3
        port: 80
        resources:
            requests:
                cpu: 10m
                memory: 100Mi
            limits:
                cpu: 500m
                memory: 1Gi
    web:
        image: stefangenov/simplesecrets-frontend
        tag: 0.5.0
        nodePort: 30000
        port: 3000
        resources:
            requests:
                cpu: 10m
                memory: 100Mi
            limits:
                cpu: 200m
                memory: 1Gi
