simplesecrets:
    image: stefangenov/simplesecrets
    tag: 1.0.7-sqlite3
    nodePort: 30125
    port: 80
    resources:
        requests:
            cpu: 10m
            memory: 100Mi
        limits:
            cpu: 500m
            memory: 1Gi
