simplesecrets:
    api:
        image: stefangenov/simplesecrets
        tag: 1.13.0-sqlite3
        nodePort: 30001
        port: 80
        resources:
            requests:
                cpu: 10m
                memory: 100Mi
            limits:
                cpu: 100m
                memory: 512Mi
    web:
        image: stefangenov/simplesecrets-frontend
        tag: 0.8.0
        nodePort: 30000
        port: 3000
        resources:
            requests:
                cpu: 10m
                memory: 100Mi
            limits:
                cpu: 200m
                memory: 1Gi
