simplesecrets:
    api:
        image: stefangenov/simplesecrets
        tag: 2.1.0
        port: 80
        resources:
            requests:
                cpu: 10m
                memory: 100Mi
            limits:
                cpu: 100m
                memory: 512Mi
    web:
        image: stefangenov/simplesecrets-frontend
        tag: 0.10.0
        port: 3000
        resources:
            requests:
                cpu: 10m
                memory: 100Mi
            limits:
                cpu: 200m
                memory: 1Gi
