# This workflow will do a clean install of NodeJS 16.x on linux for every push or pull request on master
# It will then run the tests of the app. After the tests have been run it will upload coverage reports for codacy and codecov

name: CI/CD Develop

on:
    push:
        branches: develop

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Start minikube
              uses: medyagh/setup-minikube@master
            - name: Deploy to minikube
              run: |
                  kubectl create namespace simplesecrets
                  kubectl apply -f charts/simplesecrets/templates/crd.yaml
            - name: Use Node.js 16.x
              uses: actions/setup-node@v1
              with:
                  node-version: 16.x
            - run: npm i
            - run: npm i --save sqlite3
            - run: npm run build --if-present
            - run: exports INSECURE=1
            - run: npm run test
