# This workflow will do a clean install of NodeJS 16.x on linux for every push or pull request on master
# It will then run the tests of the app. After the tests have been run it will upload coverage reports for codacy and codecov

name: linux-16.x

on:
    push:
        branches: main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Start minikube
              uses: medyagh/setup-minikube@master
            - name: Deploy to minikube
              run: |
                  kubectl create namespace simplesecrets
                  kubectl apply -f charts/simplesecrets/templates/crd.yaml
            - name: Use Node.js 16.x
              uses: actions/setup-node@v1
              with:
                  node-version: 16.x
            - run: npm i
            - run: npm run build --if-present
            - run: npm run coverage

            - name: Upload Artifact
              uses: actions/upload-artifact@v2
              with:
                  name: lcov.info
                  path: coverage/lcov.info

    codacy-coverage-reporter:
        needs: build
        runs-on: ubuntu-latest
        name: codacy-coverage-reporter
        steps:
            - uses: actions/download-artifact@v2
              with:
                  name: lcov.info
            - name: Run codacy-coverage-reporter
              uses: codacy/codacy-coverage-reporter-action@master
              with:
                  project-token: ${{ secrets.CODACY_TOKEN }}
                  coverage-reports: lcov.info
